'use client';
import { useState, useEffect } from 'react';
import Link from 'next/link';
import * as XLSX from 'xlsx';

interface UploadSummary {
  totalRows: number;
  inserted: number;
  dbDuplicates: number;
  inFileDuplicates: number;
  errorRows: number;
  autoGenerated: number;
  dbDuplicateFtNumbers: string[];
  inFileDuplicateFtNumbers: string[];
  autoGeneratedFtNumbers: { row: number; ftNumber: string }[];
  errors: { row: number; ftNumber: string; message: string }[];
}

interface ValidationError {
  row: number;
  ftNumber: string;
  message: string;
}

export default function UploadPage() {
  // State untuk autentikasi
  const [isAuthenticated, setIsAuthenticated] = useState(false);
  const [authLoading, setAuthLoading] = useState(true);
  const [loginUsername, setLoginUsername] = useState('');
  const [loginPassword, setLoginPassword] = useState('');
  const [loginError, setLoginError] = useState('');
  const [loginLoading, setLoginLoading] = useState(false);

  const [file, setFile] = useState<File | null>(null);
  const [statusMessage, setStatusMessage] = useState('');
  const [statusType, setStatusType] = useState<'idle' | 'loading' | 'success' | 'error'>('idle');
  const [uploading, setUploading] = useState(false);

  // State untuk validasi errors (pre-insertion)
  const [validationErrors, setValidationErrors] = useState<ValidationError[]>([]);

  // State untuk PIC Organ
  const [organOptions, setOrganOptions] = useState<string[]>([]);
  const [selectedOrgan, setSelectedOrgan] = useState('');

  // State untuk Generator FT Number
  const [ftGenCount, setFtGenCount] = useState('');
  const [ftGenLoading, setFtGenLoading] = useState(false);
  const [ftGenResults, setFtGenResults] = useState<string[]>([]);
  const [ftGenError, setFtGenError] = useState('');
  const [ftGenCopied, setFtGenCopied] = useState(false);

  // State untuk preview CSV
  const [previewHeaders, setPreviewHeaders] = useState<string[]>([]);
  const [previewRows, setPreviewRows] = useState<string[][]>([]);
  const [totalRows, setTotalRows] = useState(0);
  const [headerWarning, setHeaderWarning] = useState('');

  // State untuk hasil upload
  const [uploadResult, setUploadResult] = useState<UploadSummary | null>(null);

  // Cek autentikasi saat halaman dimuat
  useEffect(() => {
    const checkAuth = async () => {
      try {
        const res = await fetch('/api/auth/check?type=upload');
        const data = await res.json();
        setIsAuthenticated(data.authenticated);
      } catch {
        setIsAuthenticated(false);
      }
      setAuthLoading(false);
    };
    checkAuth();
  }, []);

  // Fetch organ options setelah authenticated
  useEffect(() => {
    if (!isAuthenticated) return;
    const fetchOrgans = async () => {
      try {
        const res = await fetch('/api/dropdown-options');
        const data = await res.json();
        setOrganOptions(data['Organ'] || []);
      } catch {
        setOrganOptions([]);
      }
    };
    fetchOrgans();
  }, [isAuthenticated]);

  const handleLogin = async (e: any) => {
    e.preventDefault();
    setLoginError('');
    setLoginLoading(true);

    try {
      const res = await fetch('/api/auth/login', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ username: loginUsername, password: loginPassword, type: 'upload' })
      });
      const data = await res.json();

      if (data.success) {
        setIsAuthenticated(true);
      } else {
        setLoginError(data.message || 'Login gagal.');
      }
    } catch {
      setLoginError('Terjadi kesalahan. Coba lagi.');
    }
    setLoginLoading(false);
  };

  const handleLogout = async () => {
    await fetch('/api/auth/logout', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ type: 'upload' })
    });
    setIsAuthenticated(false);
    setLoginUsername('');
    setLoginPassword('');
  };

  const handleGenerateFt = async () => {
    const count = parseInt(ftGenCount, 10);
    if (!count || count < 1) return setFtGenError('Masukkan jumlah minimal 1.');
    if (count > 500) return setFtGenError('Maksimal 500 FT Number sekaligus.');

    setFtGenLoading(true);
    setFtGenError('');
    setFtGenResults([]);
    setFtGenCopied(false);

    try {
      const res = await fetch('/api/generate-ft', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ count }),
      });
      const data = await res.json();
      if (res.ok) {
        setFtGenResults(data.ftNumbers || []);
      } else {
        setFtGenError(data.error || 'Gagal generate FT Number.');
      }
    } catch {
      setFtGenError('Terjadi kesalahan. Coba lagi.');
    }
    setFtGenLoading(false);
  };

  const handleCopyFt = () => {
    navigator.clipboard.writeText(ftGenResults.join('\n')).then(() => {
      setFtGenCopied(true);
      setTimeout(() => setFtGenCopied(false), 2000);
    });
  };

  const parseCSVLine = (line: string, delimiter = ','): string[] => {
    const result: string[] = [];
    let current = '';
    let inQuotes = false;

    for (let i = 0; i < line.length; i++) {
      const char = line[i];
      if (char === '"') {
        if (inQuotes && line[i + 1] === '"') {
          current += '"';
          i++;
        } else {
          inQuotes = !inQuotes;
        }
      } else if (char === delimiter && !inQuotes) {
        result.push(current.trim());
        current = '';
      } else {
        current += char;
      }
    }
    result.push(current.trim());
    return result;
  };

  const detectCSVDelimiter = (firstLine: string): string => {
    const commaCount = (firstLine.match(/,/g) || []).length;
    const semicolonCount = (firstLine.match(/;/g) || []).length;
    return semicolonCount > commaCount ? ';' : ',';
  };

  const REQUIRED_HEADERS = ['Date', 'Description', 'Amount', 'FT Number'];

  const handleFileSelect = (selectedFile: File | null) => {
    setFile(selectedFile);
    setStatusMessage('');
    setStatusType('idle');
    setPreviewHeaders([]);
    setPreviewRows([]);
    setTotalRows(0);
    setHeaderWarning('');
    setUploadResult(null);
    setValidationErrors([]);

    if (!selectedFile) return;

    const isXlsx = /\.(xlsx|xls)$/i.test(selectedFile.name);

    if (isXlsx) {
      const reader = new FileReader();
      reader.onload = (e) => {
        const buffer = e.target?.result as ArrayBuffer;
        if (!buffer) return;

        const workbook = XLSX.read(buffer, { type: 'array' });
        const sheetName = workbook.SheetNames[0];
        const sheet = workbook.Sheets[sheetName];
        const data: string[][] = XLSX.utils.sheet_to_json(sheet, { header: 1, raw: false, defval: '' });

        if (data.length === 0) return;

        const headers = data[0].map(h => String(h || '').trim());
        setPreviewHeaders(headers);

        const missing = REQUIRED_HEADERS.filter(h => !headers.includes(h));
        if (missing.length > 0) {
          setHeaderWarning(`Header tidak lengkap! Kolom yang tidak ditemukan: ${missing.join(', ')}`);
        }

        const dataLines = data.slice(1).filter(row => row.some(cell => cell !== '' && cell !== null && cell !== undefined));
        setTotalRows(dataLines.length);

        const preview = dataLines.slice(0, 10).map(row => row.map(cell => String(cell ?? '')));
        setPreviewRows(preview);
      };
      reader.readAsArrayBuffer(selectedFile);
    } else {
      const reader = new FileReader();
      reader.onload = (e) => {
        const text = e.target?.result as string;
        if (!text) return;

        const lines = text.split(/\r?\n/).filter(line => line.trim() !== '');
        if (lines.length === 0) return;

        const delimiter = detectCSVDelimiter(lines[0]);
        const headers = parseCSVLine(lines[0], delimiter);
        setPreviewHeaders(headers);

        const missing = REQUIRED_HEADERS.filter(h => !headers.includes(h));
        if (missing.length > 0) {
          setHeaderWarning(`Header tidak lengkap! Kolom yang tidak ditemukan: ${missing.join(', ')}`);
        }

        const dataLines = lines.slice(1);
        setTotalRows(dataLines.length);

        const preview = dataLines.slice(0, 10).map(line => parseCSVLine(line, delimiter));
        setPreviewRows(preview);
      };
      reader.readAsText(selectedFile);
    }
  };

  const handleUpload = async () => {
    if (!file) return alert('Pilih file dulu ya!');
    if (!selectedOrgan) return alert('Pilih PIC Organ dulu ya!');

    setStatusMessage('Sedang memproses... Tunggu sebentar');
    setStatusType('loading');
    setUploading(true);
    setUploadResult(null);
    setValidationErrors([]);

    const formData = new FormData();
    formData.append('file', file);
    formData.append('organ', selectedOrgan);

    try {
      const res = await fetch('/api/upload', {
        method: 'POST',
        body: formData,
      });
      const data = await res.json();

      if (res.ok) {
        setStatusMessage(data.message);
        setStatusType('success');
        if (data.summary) {
          setUploadResult(data.summary);
        }
        // Reset file input
        setFile(null);
        setPreviewHeaders([]);
        setPreviewRows([]);
        setTotalRows(0);
        setHeaderWarning('');
        const fileInput = document.getElementById('fileInput') as HTMLInputElement;
        if (fileInput) fileInput.value = '';
      } else if (data.validationErrors && data.validationErrors.length > 0) {
        // Validation gate triggered - show per-row errors clearly
        setValidationErrors(data.validationErrors);
        setStatusMessage(data.error || 'Upload dibatalkan karena ada kesalahan format.');
        setStatusType('error');
        // Reset file input so user can re-select the same (fixed) filename
        setFile(null);
        setPreviewHeaders([]);
        setPreviewRows([]);
        setTotalRows(0);
        setHeaderWarning('');
        const fileInput = document.getElementById('fileInput') as HTMLInputElement;
        if (fileInput) fileInput.value = '';
      } else {
        setStatusMessage(data.error || 'Gagal upload.');
        setStatusType('error');
        if (data.foundHeaders) {
          setStatusMessage(`${data.error}\n\nHeader yang ditemukan: ${data.foundHeaders.join(', ')}`);
        }
      }
    } catch (error) {
      setStatusMessage('Waduh, ada error saat upload.');
      setStatusType('error');
    }
    setUploading(false);
  };

  // Loading screen saat cek autentikasi
  if (authLoading) {
    return (
      <main className="min-h-screen bg-gradient-to-br from-emerald-50 via-white to-amber-50 flex items-center justify-center">
        <div className="text-center">
          <div className="w-8 h-8 border-4 border-emerald-600 border-t-transparent rounded-full animate-spin mx-auto mb-4"></div>
          <p className="text-gray-500 font-medium">Memuat...</p>
        </div>
      </main>
    );
  }

  // Halaman Login
  if (!isAuthenticated) {
    return (
      <main className="min-h-screen bg-gradient-to-br from-emerald-50 via-white to-amber-50 flex items-center justify-center p-4">
        <div className="w-full max-w-sm">
          <div className="bg-white rounded-2xl shadow-xl border border-emerald-100 overflow-hidden">
            {/* Header */}
            <div className="bg-gradient-to-r from-emerald-600 to-emerald-700 px-6 py-8 text-center">
              <div className="w-16 h-16 bg-white/20 rounded-full flex items-center justify-center mx-auto mb-4">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-8 h-8 text-white">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M16.5 10.5V6.75a4.5 4.5 0 1 0-9 0v3.75m-.75 11.25h10.5a2.25 2.25 0 0 0 2.25-2.25v-6.75a2.25 2.25 0 0 0-2.25-2.25H6.75a2.25 2.25 0 0 0-2.25 2.25v6.75a2.25 2.25 0 0 0 2.25 2.25Z" />
                </svg>
              </div>
              <h1 className="text-xl font-bold text-white">Upload Data Finance</h1>
              <p className="text-emerald-100 text-sm mt-1">REF 2026 - Silakan login untuk melanjutkan</p>
            </div>

            {/* Form Login */}
            <form onSubmit={handleLogin} className="p-6 flex flex-col gap-4">
              {loginError && (
                <div className="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded-lg text-sm font-medium text-center">
                  {loginError}
                </div>
              )}

              <div>
                <label className="text-xs font-bold text-gray-600 mb-1 block">Username</label>
                <input
                  type="text"
                  value={loginUsername}
                  onChange={(e) => setLoginUsername(e.target.value)}
                  className="w-full p-3 border border-gray-300 rounded-lg text-sm text-gray-900 bg-white outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-100 transition-all"
                  placeholder="Masukkan username..."
                  required
                  autoFocus
                />
              </div>

              <div>
                <label className="text-xs font-bold text-gray-600 mb-1 block">Password</label>
                <input
                  type="password"
                  value={loginPassword}
                  onChange={(e) => setLoginPassword(e.target.value)}
                  className="w-full p-3 border border-gray-300 rounded-lg text-sm text-gray-900 bg-white outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-100 transition-all"
                  placeholder="Masukkan password..."
                  required
                />
              </div>

              <button
                type="submit"
                disabled={loginLoading}
                className="mt-2 bg-gradient-to-r from-emerald-600 to-emerald-700 text-white font-bold py-3 rounded-lg hover:from-emerald-700 hover:to-emerald-800 transition-all shadow-md disabled:opacity-50 disabled:cursor-not-allowed"
              >
                {loginLoading ? 'Memproses...' : 'Masuk'}
              </button>
            </form>

            {/* Footer */}
            <div className="px-6 pb-6 text-center">
              <Link href="/" className="text-emerald-600 hover:text-emerald-800 underline text-sm font-medium">
                &larr; Kembali ke Menu Utama
              </Link>
            </div>
          </div>
        </div>
      </main>
    );
  }

  // Halaman Upload (setelah login)
  return (
    <main className="min-h-screen flex flex-col items-center justify-center bg-gradient-to-br from-emerald-50 via-white to-amber-50 p-4">
      <div className={`bg-white p-6 md:p-8 rounded-2xl shadow-xl w-full text-center border border-emerald-100 max-w-6xl`}>
        <div className="flex justify-end mb-2">
          <button
            onClick={handleLogout}
            className="text-red-500 hover:text-red-700 text-sm font-medium flex items-center gap-1 hover:bg-red-50 px-3 py-1.5 rounded-lg transition-colors"
          >
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-4 h-4">
              <path strokeLinecap="round" strokeLinejoin="round" d="M15.75 9V5.25A2.25 2.25 0 0 0 13.5 3h-6a2.25 2.25 0 0 0-2.25 2.25v13.5A2.25 2.25 0 0 0 7.5 21h6a2.25 2.25 0 0 0 2.25-2.25V15m3 0 3-3m0 0-3-3m3 3H9" />
            </svg>
            Logout
          </button>
        </div>
        <h1 className="text-2xl font-bold mb-2 text-emerald-700">Upload Data Penghimpunan</h1>
        <p className="text-sm text-gray-600 mb-6">REF 2026 - Ramadan EduAction Festival</p>

        {/* Panduan Format CSV */}
        <div className="mb-6 bg-blue-50 border border-blue-200 rounded-lg p-4 text-left text-sm">
          <div className="flex justify-between items-start mb-3">
            <h2 className="font-bold text-blue-800 flex items-center gap-2">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-5 h-5">
                <path strokeLinecap="round" strokeLinejoin="round" d="m11.25 11.25.041-.02a.75.75 0 0 1 1.063.852l-.708 2.836a.75.75 0 0 0 1.063.853l.041-.021M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Zm-9-3.75h.008v.008H12V8.25Z" />
              </svg>
              Panduan Format File
            </h2>
            <a 
              href="/template_csv_rekening_koran_BSI.xlsx"
              download
              className="inline-flex items-center gap-1.5 bg-blue-600 hover:bg-blue-700 text-white px-3 py-1.5 rounded-md text-xs font-bold transition-colors shadow-sm whitespace-nowrap"
            >
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor" className="w-4 h-4">
                <path strokeLinecap="round" strokeLinejoin="round" d="M3 16.5v2.25A2.25 2.25 0 0 0 5.25 21h13.5A2.25 2.25 0 0 0 21 18.75V16.5M16.5 12 12 16.5m0 0L7.5 12m4.5 4.5V3" />
              </svg>
              Download Template
            </a>
          </div>
          <ul className="list-disc pl-5 space-y-1.5 text-gray-700">
            <li><strong>Date:</strong> Format lengkap dengan jam, menit, detik (contoh: <code className="bg-white px-1 py-0.5 rounded border border-gray-200 text-rose-600">2/20/2026 6:55:00 AM</code>).</li>
            <li><strong>FT Number:</strong> Kunci unik transaksi. Untuk bank yang sudah memiliki FT Number (contoh: BSI), isi dari rekening koran. Untuk bank tanpa FT Number (BCA Syariah, BJB, dll), gunakan <strong>Generator FT Number</strong> di bawah ini, atau kosongkan — sistem akan auto-generate kode 9 karakter saat upload.</li>
            <li><strong>Description:</strong> Akan dipecah menjadi <em>Keterangan</em> dan <em>Nama Donatur</em>, wajib dipisah dengan tanda strip (<code className="bg-white px-1 py-0.5 rounded border border-gray-200 text-rose-600">-</code>). <br/><span className="text-xs text-gray-500 mt-1 block">Contoh: <code className="bg-white px-1 py-0.5 rounded border border-gray-100 text-rose-600">TUNAI Keropak Jumat - Sekolah SMART Cibinong</code> atau <code className="bg-white px-1 py-0.5 rounded border border-gray-100 text-rose-600">BARANG 500 Mainan untuk RDP Sumatera - Sekolah SMART Cibinong</code></span></li>
            <li><strong>Currency:</strong> Format teks <code className="bg-white px-1 py-0.5 rounded border border-gray-200 text-rose-600">IDR</code>.</li>
            <li><strong>Amount:</strong> Format number 2 digit di belakang koma (isi cell harus angka), contoh <code className="bg-white px-1 py-0.5 rounded border border-gray-200 text-rose-600">259045</code> (layar menampilkan 259,045.00).</li>
            <li>Kolom <strong>DB</strong>, <strong>CR</strong>, dan <strong>Balance</strong> dapat dikosongkan.</li>
          </ul>
        </div>

        {/* Generator FT Number */}
        <details className="mb-6 bg-violet-50 border border-violet-200 rounded-xl overflow-hidden">
          <summary className="px-4 py-3 cursor-pointer text-sm font-bold text-violet-800 hover:bg-violet-100 transition-colors flex items-center gap-2 list-none">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-5 h-5 flex-shrink-0">
              <path strokeLinecap="round" strokeLinejoin="round" d="M9.75 3.104v5.714a2.25 2.25 0 0 1-.659 1.591L5 14.5M9.75 3.104c-.251.023-.501.05-.75.082m.75-.082a24.301 24.301 0 0 1 4.5 0m0 0v5.714c0 .597.237 1.17.659 1.591L19.8 15.3M14.25 3.104c.251.023.501.05.75.082M19.8 15.3l-1.57.393A9.065 9.065 0 0 1 12 15a9.065 9.065 0 0 1-6.23-.693L5 14.5m14.8.8 1.402 1.402c1.232 1.232.65 3.318-1.067 3.611A48.309 48.309 0 0 1 12 21c-2.773 0-5.491-.235-8.135-.687-1.718-.293-2.3-2.379-1.067-3.61L5 14.5" />
            </svg>
            Generator FT Number — Untuk bank yang tidak memiliki FT Number
          </summary>
          <div className="px-4 pb-4 pt-3 text-left">
            <p className="text-xs text-violet-600 mb-3">
              Generate FT Number unik 9 karakter (A–Z, 0–9) untuk dipastekan ke kolom <strong>FT Number</strong> di file CSV sebelum upload.
              Sistem otomatis mengecek keunikan ke database.
            </p>
            <div className="flex gap-2 items-end flex-wrap">
              <div className="flex-1 min-w-[140px]">
                <label className="text-xs font-bold text-violet-700 mb-1 block">Jumlah FT Number</label>
                <input
                  type="number"
                  min={1}
                  max={500}
                  value={ftGenCount}
                  onChange={(e) => { setFtGenCount(e.target.value); setFtGenError(''); }}
                  placeholder="Contoh: 57"
                  className="w-full p-2.5 border border-violet-300 rounded-lg text-sm text-gray-900 bg-white outline-none focus:border-violet-500 focus:ring-2 focus:ring-violet-100 transition-all"
                />
              </div>
              <button
                onClick={handleGenerateFt}
                disabled={ftGenLoading || !ftGenCount}
                className="bg-violet-600 hover:bg-violet-700 disabled:opacity-50 disabled:cursor-not-allowed text-white font-bold px-4 py-2.5 rounded-lg text-sm transition-colors shadow-sm whitespace-nowrap"
              >
                {ftGenLoading ? 'Generating...' : 'Generate'}
              </button>
            </div>

            {ftGenError && (
              <p className="mt-2 text-xs text-red-600 font-medium">{ftGenError}</p>
            )}

            {ftGenResults.length > 0 && (
              <div className="mt-4">
                <div className="flex items-center justify-between mb-2">
                  <p className="text-xs font-bold text-violet-700">{ftGenResults.length} FT Number berhasil di-generate:</p>
                  <button
                    onClick={handleCopyFt}
                    className={`flex items-center gap-1.5 text-xs font-bold px-3 py-1.5 rounded-lg transition-colors ${
                      ftGenCopied
                        ? 'bg-emerald-100 text-emerald-700'
                        : 'bg-violet-100 hover:bg-violet-200 text-violet-700'
                    }`}
                  >
                    {ftGenCopied ? (
                      <>
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor" className="w-3.5 h-3.5">
                          <path strokeLinecap="round" strokeLinejoin="round" d="m4.5 12.75 6 6 9-13.5" />
                        </svg>
                        Tersalin!
                      </>
                    ) : (
                      <>
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-3.5 h-3.5">
                          <path strokeLinecap="round" strokeLinejoin="round" d="M15.666 3.888A2.25 2.25 0 0 0 13.5 2.25h-3c-1.03 0-1.9.693-2.166 1.638m7.332 0c.055.194.084.4.084.612v0a.75.75 0 0 1-.75.75H9a.75.75 0 0 1-.75-.75v0c0-.212.03-.418.084-.612m7.332 0c.646.049 1.288.11 1.927.184 1.1.128 1.907 1.077 1.907 2.185V19.5a2.25 2.25 0 0 1-2.25 2.25H6.75A2.25 2.25 0 0 1 4.5 19.5V6.257c0-1.108.806-2.057 1.907-2.185a48.208 48.208 0 0 1 1.927-.184" />
                        </svg>
                        Copy Semua
                      </>
                    )}
                  </button>
                </div>
                <div className="bg-white border border-violet-200 rounded-lg p-3 max-h-48 overflow-y-auto">
                  <div className="grid grid-cols-3 sm:grid-cols-4 md:grid-cols-5 gap-1.5">
                    {ftGenResults.map((ft, i) => (
                      <span key={i} className="font-mono text-xs bg-violet-50 text-violet-800 px-2 py-1 rounded border border-violet-100 text-center tracking-wider">
                        {ft}
                      </span>
                    ))}
                  </div>
                </div>
                <p className="text-xs text-violet-500 mt-2">
                  Paste ke kolom <strong>FT Number</strong> di file CSV (satu FT Number per baris), lalu upload file.
                </p>
              </div>
            )}
          </div>
        </details>

        {/* PIC Organ Selector */}
        <div className="mb-4 text-left">
          <label className="text-xs font-bold text-gray-600 mb-1 block">PIC Finance (Organ)</label>
          <select
            value={selectedOrgan}
            onChange={(e) => setSelectedOrgan(e.target.value)}
            className="w-full p-3 border border-gray-300 rounded-lg text-sm text-gray-900 bg-white outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-100 transition-all"
          >
            <option value="">-- Pilih Organ --</option>
            {organOptions.map((opt, i) => (
              <option key={i} value={opt}>{opt}</option>
            ))}
          </select>
        </div>

        <input
          id="fileInput"
          type="file"
          accept=".csv,.xlsx,.xls"
          onChange={(e) => handleFileSelect(e.target.files?.[0] || null)}
          className="block w-full text-sm text-gray-500 mb-4 cursor-pointer
            file:mr-4 file:py-2 file:px-4 file:rounded-lg file:border-0
            file:text-sm file:font-semibold file:bg-emerald-50 file:text-emerald-700 hover:file:bg-emerald-100"
        />

        {/* Peringatan Header */}
        {headerWarning && (
          <div className="mb-4 bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded-lg text-sm text-left">
            <p className="font-bold mb-1">Format CSV Tidak Sesuai</p>
            <p>{headerWarning}</p>
            <p className="mt-2 text-xs text-red-500">Header yang dibutuhkan: {REQUIRED_HEADERS.join(', ')}</p>
          </div>
        )}

        {/* Preview Tabel CSV */}
        {previewRows.length > 0 && (
          <div className="mb-4 text-left">
            <div className="flex items-center justify-between mb-3">
              <h3 className="text-sm font-bold text-gray-700">Preview Data ({totalRows} baris total, menampilkan 10 baris pertama)</h3>
            </div>
            <div className="overflow-x-auto border border-gray-200 rounded-lg">
              <table className="w-full text-left border-collapse text-xs">
                <thead>
                  <tr className="bg-emerald-50 text-emerald-800 border-b border-gray-200">
                    <th className="p-2 font-bold text-center border-r border-gray-200 whitespace-nowrap">#</th>
                    {previewHeaders.map((header, i) => (
                      <th key={i} className={`p-2 font-bold whitespace-nowrap border-r border-gray-200 last:border-r-0 ${REQUIRED_HEADERS.includes(header) ? '' : 'text-gray-400'}`}>{header}</th>
                    ))}
                  </tr>
                </thead>
                <tbody className="text-gray-700">
                  {previewRows.map((row, rowIdx) => (
                    <tr key={rowIdx} className="border-b border-gray-100 hover:bg-gray-50">
                      <td className="p-2 text-center text-gray-400 font-medium border-r border-gray-200 whitespace-nowrap">{rowIdx + 1}</td>
                      {row.map((cell, cellIdx) => (
                        <td key={cellIdx} className="p-2 whitespace-nowrap border-r border-gray-200 last:border-r-0 max-w-[200px] truncate" title={cell}>{cell || '-'}</td>
                      ))}
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
            {totalRows > 10 && (
              <p className="text-xs text-gray-400 mt-2 text-center">... dan {totalRows - 10} baris lainnya</p>
            )}
          </div>
        )}

        <button
          onClick={handleUpload}
          disabled={!file || !selectedOrgan || uploading || !!headerWarning}
          className="w-full bg-gradient-to-r from-emerald-600 to-emerald-700 text-white py-2 rounded-lg font-bold hover:from-emerald-700 hover:to-emerald-800 transition-all shadow-md hover:shadow-lg mb-4 disabled:opacity-50 disabled:cursor-not-allowed"
        >
          {uploading ? 'Sedang Memproses...' : 'Proses & Kirim Data Finance'}
        </button>

        {/* Status Message */}
        {statusMessage && statusType !== 'idle' && (
          <div className={`mt-4 px-4 py-3 rounded-lg text-sm font-medium text-left whitespace-pre-line ${
            statusType === 'loading' ? 'bg-blue-50 border border-blue-200 text-blue-700' :
            statusType === 'success' ? 'bg-emerald-50 border border-emerald-200 text-emerald-700' :
            'bg-red-50 border border-red-200 text-red-700'
          }`}>
            {statusMessage}
          </div>
        )}

        {/* Validasi Error Table (pre-insertion) */}
        {validationErrors.length > 0 && (
          <div className="mt-4 text-left">
            <div className="bg-red-50 border border-red-300 rounded-xl overflow-hidden">
              <div className="px-4 py-3 bg-red-100 border-b border-red-300">
                <p className="text-sm font-bold text-red-800 flex items-center gap-2">
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor" className="w-4 h-4">
                    <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126ZM12 15.75h.007v.008H12v-.008Z" />
                  </svg>
                  Upload Dibatalkan — {validationErrors.length} Baris Bermasalah Ditemukan
                </p>
                <p className="text-xs text-red-600 mt-1">Tidak ada data yang disimpan. Perbaiki semua baris di bawah ini, lalu upload ulang.</p>
              </div>
              <div className="overflow-x-auto max-h-72 overflow-y-auto">
                <table className="w-full text-xs">
                  <thead className="sticky top-0 bg-red-100">
                    <tr className="text-left text-red-700">
                      <th className="px-4 py-2 whitespace-nowrap">Baris (CSV)</th>
                      <th className="px-4 py-2 whitespace-nowrap">FT Number</th>
                      <th className="px-4 py-2">Keterangan Kesalahan</th>
                    </tr>
                  </thead>
                  <tbody className="text-red-800">
                    {validationErrors.map((err, i) => (
                      <tr key={i} className="border-t border-red-200 hover:bg-red-100">
                        <td className="px-4 py-2 font-mono font-bold">{err.row}</td>
                        <td className="px-4 py-2 font-mono">{err.ftNumber || '-'}</td>
                        <td className="px-4 py-2">{err.message}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        )}

        {/* Hasil Upload Detail */}
        {uploadResult && (
          <div className="mt-4 text-left">
            {/* Ringkasan Angka */}
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(5, 1fr)', gap: '0.75rem' }} className="mb-4">
              <div className="bg-gray-50 rounded-lg p-3 text-center border">
                <p className="text-2xl font-bold text-gray-700">{uploadResult.totalRows}</p>
                <p className="text-xs text-gray-500">Total Baris</p>
              </div>
              <div className="bg-emerald-50 rounded-lg p-3 text-center border border-emerald-200">
                <p className="text-2xl font-bold text-emerald-600">{uploadResult.inserted}</p>
                <p className="text-xs text-emerald-600">Berhasil Masuk</p>
              </div>
              <div className={`rounded-lg p-3 text-center border ${uploadResult.autoGenerated > 0 ? 'bg-blue-50 border-blue-200' : 'bg-gray-50'}`}>
                <p className={`text-2xl font-bold ${uploadResult.autoGenerated > 0 ? 'text-blue-600' : 'text-gray-400'}`}>{uploadResult.autoGenerated}</p>
                <p className={`text-xs ${uploadResult.autoGenerated > 0 ? 'text-blue-600' : 'text-gray-400'}`}>Auto-Generate FT</p>
              </div>
              <div className="bg-yellow-50 rounded-lg p-3 text-center border border-yellow-200">
                <p className="text-2xl font-bold text-yellow-600">{uploadResult.dbDuplicates + uploadResult.inFileDuplicates}</p>
                <p className="text-xs text-yellow-600">Di-skip (Duplikat)</p>
              </div>
              <div className={`rounded-lg p-3 text-center border ${uploadResult.errorRows > 0 ? 'bg-red-50 border-red-200' : 'bg-gray-50'}`}>
                <p className={`text-2xl font-bold ${uploadResult.errorRows > 0 ? 'text-red-600' : 'text-gray-400'}`}>{uploadResult.errorRows}</p>
                <p className={`text-xs ${uploadResult.errorRows > 0 ? 'text-red-600' : 'text-gray-400'}`}>Baris Error</p>
              </div>
            </div>

            {/* Detail FT Number Auto-Generated */}
            {uploadResult.autoGeneratedFtNumbers && uploadResult.autoGeneratedFtNumbers.length > 0 && (
              <details className="mb-3 bg-blue-50 border border-blue-200 rounded-lg">
                <summary className="px-4 py-2 cursor-pointer text-sm font-bold text-blue-700 hover:bg-blue-100 rounded-lg">
                  FT Number di-generate otomatis ({uploadResult.autoGenerated} baris)
                </summary>
                <div className="px-4 pb-3 max-h-60 overflow-y-auto">
                  <table className="w-full text-xs mt-2">
                    <thead>
                      <tr className="text-left text-blue-600">
                        <th className="pb-1 pr-3">Baris</th>
                        <th className="pb-1">FT Number (Generated)</th>
                      </tr>
                    </thead>
                    <tbody className="text-blue-700">
                      {uploadResult.autoGeneratedFtNumbers.map((item, i) => (
                        <tr key={i} className="border-t border-blue-100">
                          <td className="py-1 pr-3 font-mono">{item.row}</td>
                          <td className="py-1 font-mono">{item.ftNumber}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                  {uploadResult.autoGenerated > 50 && (
                    <p className="text-xs text-blue-400 mt-2">Menampilkan 50 pertama dari {uploadResult.autoGenerated} total.</p>
                  )}
                </div>
              </details>
            )}

            {/* Detail FT Number Duplikat dari Database */}
            {uploadResult.dbDuplicateFtNumbers.length > 0 && (
              <details className="mb-3 bg-yellow-50 border border-yellow-200 rounded-lg">
                <summary className="px-4 py-2 cursor-pointer text-sm font-bold text-yellow-700 hover:bg-yellow-100 rounded-lg">
                  FT Number sudah ada di database ({uploadResult.dbDuplicates} baris di-skip)
                </summary>
                <div className="px-4 pb-3 max-h-40 overflow-y-auto">
                  <div className="flex flex-wrap gap-1 mt-2">
                    {uploadResult.dbDuplicateFtNumbers.map((ft, i) => (
                      <span key={i} className="inline-block bg-yellow-100 text-yellow-800 text-xs px-2 py-1 rounded font-mono">{ft}</span>
                    ))}
                  </div>
                </div>
              </details>
            )}

            {/* Detail FT Number Duplikat dalam File */}
            {uploadResult.inFileDuplicateFtNumbers.length > 0 && (
              <details className="mb-3 bg-orange-50 border border-orange-200 rounded-lg">
                <summary className="px-4 py-2 cursor-pointer text-sm font-bold text-orange-700 hover:bg-orange-100 rounded-lg">
                  FT Number duplikat dalam file ({uploadResult.inFileDuplicates} baris di-skip)
                </summary>
                <div className="px-4 pb-3 max-h-40 overflow-y-auto">
                  <div className="flex flex-wrap gap-1 mt-2">
                    {uploadResult.inFileDuplicateFtNumbers.map((ft, i) => (
                      <span key={i} className="inline-block bg-orange-100 text-orange-800 text-xs px-2 py-1 rounded font-mono">{ft}</span>
                    ))}
                  </div>
                </div>
              </details>
            )}

            {/* Detail Error per Baris */}
            {uploadResult.errors.length > 0 && (
              <details className="mb-3 bg-red-50 border border-red-200 rounded-lg">
                <summary className="px-4 py-2 cursor-pointer text-sm font-bold text-red-700 hover:bg-red-100 rounded-lg">
                  Detail error per baris ({uploadResult.errorRows} baris)
                </summary>
                <div className="px-4 pb-3 max-h-60 overflow-y-auto">
                  <table className="w-full text-xs mt-2">
                    <thead>
                      <tr className="text-left text-red-600">
                        <th className="pb-1 pr-3">Baris</th>
                        <th className="pb-1 pr-3">FT Number</th>
                        <th className="pb-1">Error</th>
                      </tr>
                    </thead>
                    <tbody className="text-red-700">
                      {uploadResult.errors.map((err, i) => (
                        <tr key={i} className="border-t border-red-100">
                          <td className="py-1 pr-3 font-mono">{err.row}</td>
                          <td className="py-1 pr-3 font-mono">{err.ftNumber}</td>
                          <td className="py-1">{err.message}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                  {uploadResult.errorRows > 50 && (
                    <p className="text-xs text-red-400 mt-2">Menampilkan 50 error pertama dari {uploadResult.errorRows} total.</p>
                  )}
                </div>
              </details>
            )}
          </div>
        )}

        <Link href="/" className="block mt-6 text-sm text-gray-500 hover:text-emerald-600 underline">
          &larr; Kembali ke Beranda
        </Link>
      </div>
    </main>
  );
}
